### PR TITLE
Added internationalization support and Italian translation for the Mac OS X version

### PR DESCRIPTION
**Pull request by ghost**
Added internationalization support using gettext and Italian translation for the Mac OS X version.
There are some stock buttons that are not translatable yet (like Forward and Go Back buttons) because their text is probably part of the Qt library. I've already read something around the web and it seems to be easy to solve because Qt also includes translations for stock buttons, I just have to figure out how to activate them. There is just a visual bug in the download dialog in which a part of the translated text overflows and get hidden (the label doesn't automatically return like in the other dialogs) so I will look into it, but it seems like a minor glitch.

Please, tell me what you think.

Thanks
CB

### CODE REVIEW

**Comment by ghost** [comment]
This is related to [issue 7](https://github.com/cznweb/arkos-install/issues/7).

**Comment by peakwinter** [comment]
This looks great. I will have support extended to the Linux version, as well as set up the translation server with the generated files.

Thanks so much!!

**Comment by elimisteve** [comment]
+1, nice!

**Comment by ghost** [comment]
Happy to contribute! :-)
Thanks for starting this project. Since the Raspberry Pi came out I looked for something like this and I was thinking of starting a project of my own but then a friend of mine chanced upon yours and told me. It's exactly what I wanted, so I will try to contribute in any way I can!

**Pull request merged**
